### ISSUE TITLE
clickable marker

### ISSUE THREAD

**Issue by mahansh** [NeshanMaps/android-neshan-maps-starter#13]
با سلام
من میخوام در این نقشه مارک ها قابلیت کلیک داشته باشند
با توجه به اینکه نقشه گوگل این قابلیت را دارد و با متد تعریف میکند ایا نقشه نشان هم این قابلیت را دارد؟
اگر دارد چطور؟

**Comment by mostafa-j13** [comment]
https://github.com/NeshanMaps/android-neshan-maps-starter/issues/2
