### ISSUE TITLE
how to show pixel prefect bitmap on map?

### ISSUE THREAD

**Issue by ali-star** [NeshanMaps/android-neshan-maps-starter#3]
i have a bitmap with 36dp width and height and i want to show it as pixel perfect bitmap on map but it's get blurry on map...

i specify the size with pixels (converting dp to pixels):
```
markerStyleCreator.setSize(DimensionUtils.dipToPix(36));
```

**Comment by mostafa-j13** [comment]
its better to use power 2 size bitmap like 16,32,64 pixel
