### ISSUE TITLE
برای قرار دادن دیتا مثلا نام مکان داخل مارکر چکار باید کرد؟ 

### ISSUE THREAD

**Issue by iceboy1369** [NeshanMaps/android-neshan-maps-starter#7]
روی نقشه مارکر هایی دارم و میخوام بعد از کلیک کردن روی آن ها یک داده ای از آن بهم برگرده مثلا نام مکان؟

**Comment by mostafa-j13** [comment]
موقع اضافه کردن مارکر می‌تونید اطلاعات رو داخل مارکر ذخیره کنید
با کمک این متدهایی مثل
https://developers.neshan.org/android-sdk/reference/0.9.5/reference/org/neshan/vectorelements/Element.html#setMetaData(org.neshan.core.StringVariantMap)
 بعد موقع کلیک شدن می‌تونید این اطلاعات رو دوباره بگیرید
