### ISSUE TITLE
onCameraMove?!

### ISSUE THREAD

**Issue by iceboy1369** [NeshanMaps/android-neshan-maps-starter#8]
با سلام
معادل onCameraMove در گوگل من رو میخواستم ببینم اینجا باید از چه تابعی و لیستنری استفاده کنم؟

**Comment by mostafa-j13** [comment]
با این کلاس می تونید این کار رو بکنید
https://developers.neshan.org/android-sdk/reference/0.9.5/reference/org/neshan/ui/MapEventListener.html

مثالش اینجاست
https://github.com/NeshanMaps/android-neshan-maps-starter/wiki/%D8%AA%D8%BA%DB%8C%DB%8C%D8%B1-%D8%AC%D9%87%D8%AA-%D8%AF%D9%88%D8%B1%D8%A8%DB%8C%D9%86
